### ISSUE TITLE
Button Text Alignment Issues On Arch Linux

### ISSUE THREAD

**Issue by DoctorJax** [TriLinder/StreamDeckController#1]
This is my first time creating an issue on any project, so I'll try to keep it short and sweet.

### Describe bug
Text on buttons are misaligned and longer words are cut off. 

### Operating System
OS: Arch Linux
Kernel: 5.17.1-zen1-1-zen
Python version: Python 3.10.4
StreamDeck version: V2 - 15 button

### Suggested solution
In the `controller.py` file,  the following lines seem to be what causes it.
```python
if system == "windows" : #Fixing weird bug
    x = image.width / 2
else :
    x = image.width / 2 - (w/2)
```
More specifically, the else statement that includes `x = image.width / 2 - (w/2)` seems to be the issue.

I was messing with things, and by removing the `- (w/2)` at the end of the else statement, the issue seems to be fixed. Thus, I don't think the if statement is even needed (can just be replaced with `x = image.width / 2` instead), as when I changed the `system == "windows"` to `system == "linux"` in the if statement, it worked as expected.

### Expected behavior
The text should be centered left and right and words shouldn't be cut off, like the example images in the README and in the showcase post on Reddit.

**Comment by TriLinder** [comment]
Sorry for taking so long to respond, and a huge thank you for the detailed bug report.
After testing on multiple operating systems, I found that some require the `- (w/2)` part, while some don't.

I'm still a noob when it comes to programming, and I couldn't figure out why this happened, so for now I added a `fontCenterFix` key to the config. Setting it to `true` should fix your issue without having to modify the code yourself.

While I'm not that happy with my fix, I think it's enough to consider the issue closed.
Thank you.
