### ISSUE TITLE
Running Commands With Flags Results In "No such file or directory" On Arch Linux

### ISSUE THREAD

**Issue by DoctorJax** [TriLinder/StreamDeckController#2]
### Describe Bug
Unable to run commands with "runCommand" action that use flags (i.e. `alacritty -e 'htop'`). Instead it just gives an error of: `No such file or directory`.

### Operating System
OS: Arch Linux
Kernel: 5.17.7-zen1-1-zen
Python version: Python 3.10.4
StreamDeck version: V2 - 15 button

### Suggested Solution
In the `controller.py` file, this is the line which controls the "runCommand" action:
```python
elif action == "runCommand" :
     subprocess.call(str(actionData), stderr=subprocess.DEVNULL)
```
To allow commands to be used with flags and other shell modifiers, the line: 
`subprocess.call(str(actionData), stderr=subprocess.DEVNULL)`
should instead be:
`subprocess.call(str(actionData), shell=True, stderr=subprocess.DEVNULL)`

In which **shell=True** fixes the issue.

### Expected Behavior
Should be able to run commands with flags and other shell based modifiers (i.e. `alacritty -e 'htop' &`).

**Comment by TriLinder** [comment]
Once again, sorry for taking so long to respond and a million thanks to you for writing up such a detailed issue.
It should now be fixed.
